server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore
    username: root
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
