server:
  port: 8082
spring:
  application:
    name: SUBSCRIPTION-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore
    username: root
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka