server:
  port: 8081
spring:
  application:
    name: book-service
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore
    username: root
    password: password
  jpa:
    show-sql: true
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka